### ISSUE TITLE
@ doesn't work for js config?

### ISSUE THREAD

**Issue by aliyss** [tehZevo/configbot#3]
```js
responses: {
    ping: "pong",
    @onlymention: "error in code"
  }
```

**Suggestion:** Use $ instead.

**Comment by tehZevo** [comment]
The reason I chose @, was since it's used for Discord mentions, it'd be unlikely that someone would use it in their actual text, which would otherwise force some checks for "escaped" @'s (or $'s), I'll consider it though.
